Add the feature to ignore folders and paths with globbing

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -10,50 +10,56 @@ function homepath {
 
 function collect {
 
+	# Create the repo folder if it's not present
+	mkdir -p $REPO
+
 	# There is a global versioned white/blacklist and there is a local one
 	whitelist=`cat $HERE/whitelist.txt $HOME/.dotfiles/whitelist.txt 2> /dev/null`
 	blacklist=`cat $HERE/blacklist.txt $HOME/.dotfiles/blacklist.txt 2> /dev/null`
 
-	# Create the repo folder if it's not present
-	mkdir -p $REPO
+	# Remove empty lines
+	whitelist=`echo "$whitelist" | grep -v '^$'`
+	blacklist=`echo "$blacklist" | grep -v '^$'`
 
-	# For each whitelisted file and folder
-	for filepath in $whitelist; do
+	# Check if the whitelist is empty
+	if ! [ -n "$whitelist" ]; then
+		echo "Error: the whitelist can not be empty"
+		exit 1
+	fi
 
-		# The whitelisted files path is relative
-		# to the home folder
-		filepath=$HOME/$filepath
+	# Make a string with all the whitelisted files (separated by space)
+	search=`echo -n "$whitelist" | perl -p -e "s#\n#\" \"$HOME/#"`
+	search="\"$HOME/$search\""
 
-		# Get the file name without the path
-		filename=`basename $filepath`
+	# Check if there is anything blacklisted
+	if [ -n "$blacklist" ]; then
+		blacklist=`echo -n "$blacklist" | perl -p -e "s#/\\$##"`
+		ignore=`echo -n "$blacklist" | perl -p -e "s#\n#\" -o -path \"$HOME/#"`
+		ignore="\( -path \"$ignore\" \) -prune -o -print"
+	else
+		ignore=""
+	fi
 
-		# If this is a file: the list will have it's path
-		# If this is a folder: the list will comntain the
-		# folder`s path and it's containg files paths
-		content=`find $filepath`
+	files=`eval find $search $ignore 2> /dev/null`
 
-		# For each entry in the list
-		for childpath in $content; do
+	# For each entry in the list
+	for filepath in $files; do
 
-			# Get the path relative to the home folder
-			childname=`homepath $childpath`
+		# Get the path relative to the home folder
+		filename=`homepath $filepath`
 
-			# Check if the file is not blacklisted
-			if ! echo "$blacklist" | grep "^$childname$" &> /dev/null; then
-				# If it's a folder we don't need it
-				if [ -f $childpath ]; then
-					# Show the file name for tracing
-					echo $childname
+		# If it's a folder we don't need it
+		if [ -f $filepath ]; then
+			# Show the file name for tracing
+			echo $filename
 
-					# If the folder containing the
-					# file does not exit create it
-					mkdir -p "$REPO/`dirname $childname`"
+			# If the folder containing the
+			# file does not exit create it
+			mkdir -p "$REPO/`dirname $filename`"
 
-					# Copy the file
-					cp $childpath $REPO/$childname
-				fi
-			fi
-		done
+			# Copy the file
+			cp $filepath $REPO/$filename
+		fi
 	done
 }
 
